const fake = require('./lib')
const test = v => console.log(fake(v))
test('@name')
test('@boolean')
test('@natural(1, 5)')
test('@integer(1, 5)')
test('@float(1, 5, 2,3)')
test('@character')
test('@string')
test('@range(1,10,2)')
test('@date')
test('@time')
test('@datetime')
test('@now')
test("@image('200x100', '#50B347', '#FFF', 'fake.js')")
test('@paragraph(1,3)')
test('@sentence(1,3)')
test('@word(2,8)')
test('@title(2,8)')
test('@first')
test('@last')
test('@name')
test('@url')
test('@domain')
test('@email')
test('@ip')
test('@guid')
